### ISSUE TITLE
Implement SVM and evaluation

### ISSUE THREAD

**Issue by simondewit** [simondewit/pickleteam#2]

**Comment by hslh** [comment]
Try varying word n-grams and character n-grams and the combination of the two.

**Comment by hslh** [comment]
For combining the features (e.g. character and word n-grams), FeatureUnion is probably the easiest to use.

**Comment by hslh** [comment]
Try word 1- and 2-grams, bigger n-grams for characters, e.g. 3-5 grams.

**Comment by hslh** [comment]
And also combine the word and character n-grams.

**Comment by hslh** [comment]
^^

**Comment by hslh** [comment]
Something like this is how FeatureUnion can be used to do the combination (pretty straightforward): 
```python
Pipeline([('features', FeatureUnion([('wrd', TfidfVectorizer()), ('char',TfidfVectorizer(analyzer='char'))]))
```
